version: '3.8'

services:
  # O Banco de Dados
  postgres-db:
    image: postgres:15-alpine
    container_name: decifra-db
    environment:
      POSTGRES_USER: user_decifra
      POSTGRES_PASSWORD: password_decifra
      POSTGRES_DB: decifra_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Ferramenta visual para ver o banco (Opcional, mas ajuda muito)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-decifra
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@decifra.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

volumes:
  postgres_data: